### ISSUE TITLE
Build failure due to deprecated action

### ISSUE THREAD

**Issue by lmmx** [ion-elgreco/polars-distance#33]
- GitHub has deprecated the v3 of the upload-actions action 
- I submitted a patch in #32 that will fix this

Dependabot could suggest these sorts of upgrades automatically if we put this file in `.github/dependabot.yml` (as described [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)):

```yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

(Or "monthly" etc for less frequent notifications)
